### ISSUE TITLE
Allow to async return a glTF after all resources are loaded

### ISSUE THREAD

**Issue by georgios-uber** [uber/luma.gl#1025]
#### Background 
deck.gl needs to get a renderable model.

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
> deck.gl needs to get a renderable model.

luma.gl handles async textures (by skipping `Program.draw()` until all texture-values uniforms are loaded). Does that not work in deck? 

Or is this not related to textures?

**Comment by georgios-uber** [comment]
> > deck.gl needs to get a renderable model.
> 
> luma.gl handles async textures (by skipping `Program.draw()` until all texture-values uniforms are loaded). Does that not work in deck?
> 
> Or is this not related to textures?

This logic breaks _constant attributes_.

**Comment by ibgreen** [comment]
What logic? Checking if the textures are renderable breaks constant attributes?

**Comment by georgios-uber** [comment]
Yup. Took me from 2am yesterday till 3am to figure it out!

**Comment by georgios-uber** [comment]
Yup. Took me an hour yesterday to figure it out.

**Comment by ibgreen** [comment]
In that case, should we fix it in luma.gl instead of trying to change the glTF loader?

**Comment by georgios-uber** [comment]
The second problem is that when the props change it triggers **one** render.
If the texture is not here the use has to pan the map to see our ducks 🦆

**Comment by ibgreen** [comment]
Yes, and deck.gl no longer checks dirty state on models so we can't just set the dirty state on load.

To avoid getting stuck on that, makes sense to have an option that waits for all textures to load. 

Still don't understand the constant attributes issue though, but sounds like it will be fixed by this.

**Comment by georgios-uber** [comment]
> Still don't understand the constant attributes issue though, but sounds like it will be fixed by this.

It won't be _fixed_, it's just a workaround.

**Comment by georgios-uber** [comment]
ok... seems like the constant fix is maybe unrelated.
@Pessimistress Can you help debug the constant attribute?

**Comment by georgios-uber** [comment]
https://github.com/uber/luma.gl/pull/1029
