### ISSUE TITLE
SphereGeometry generates upside-down UVs

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#1027]
`v` is 0 when `uy` is 1 here: https://github.com/uber/luma.gl/blob/master/modules/core/src/geometries/sphere-geometry.js#L40-L55

**Comment by ibgreen** [comment]
Ah, so that is why the earth in example 15 used to be upside down...

**Comment by tsherif** [comment]
Exactly! What do you think? Should I just fix it or is there some risk of breakage somewhere?

**Comment by ibgreen** [comment]
I would just fix it. I don't foresee much breakage, and it is a major release after all.
