### ISSUE TITLE
Use 'instance of' operator to verify WebGL context version

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#1055]
Follow up task for #1048
More details in #1053 

We create a debug context using a third party module `webgl-debug`.
```
const debugContext = WebGLDebug.makeDebugContext(gl, onGLError, onValidateGLFunc);
```
https://github.com/uber/luma.gl/blob/006e02d1c3b17e27580ab2d0eb1599b30fa4938b/modules/debug/src/webgl-api-tracing/webgl-debug-context.js#L63

This creates wrapper object around actual context object and hence `instance of` operator fails on these objects. Copy all this code and use proper inheritance so new wrapper object is either instance of `WebGLRenderingContext` or `WebGL2RenderingContext`.

**Comment by tsherif** [comment]
I'm against doing this unless there's a functional problem with the current solution. It's adding a lot more complexity for a less robust, harder-to-maintain test.

**Comment by ibgreen** [comment]
Agreed. we'll stay with the `isWebGL` checks, we can keep checking the `gl.version` field inside those functions.

Any change to how we create the debug context (for purposes of improving the debug experience) will thus be invisible to the rest of the library.
