### ISSUE TITLE
Framebuffer documentation mistake

### ISSUE THREAD

**Issue by Tirondzo** [uber/luma.gl#1097]
```js
this.rttFrameBuffer = new Framebuffer(gl, {
  width: resolution, height: resolution,
  attachments: {
    [GL.COLOR_ATTACHMENT_0]: [this.rttCubemap, GL.TEXTURE_CUBE_MAP_POSITIVE_X],
    [GL.DEPTH_ATTACHMENT]: renderbuffer
  }
});
```
> VM72985 texture-cube.js:106 Uncaught (in promise) TypeError: Cannot read property '34069' of null
    at eval (VM72985 texture-cube.js:106)
    at Array.map (<anonymous>)
    at TextureCube._callee$ (VM72985 texture-cube.js:105)
    at tryCatch (VM72987 runtime.js:45)
    at Generator.invoke [as _invoke] (VM72987 runtime.js:271)
    at Generator.prototype.<computed> [as next] (VM72987 runtime.js:97)
    at asyncGeneratorStep (VM72988 asyncToGenerator.js:5)
    at _next (VM72988 asyncToGenerator.js:27)
    at eval (VM72988 asyncToGenerator.js:34)
    at new Promise (<anonymous>)

#### A little more info:
For some reason `opts` in framebuffer constructor is:
> {36096: Renderbuffer, undefined: Array(2)}  

Seems like GL.COLOR_ATTACHMENT_0 is undefined

#### Workaround is:
```js
this.rttFrameBuffer = new Framebuffer(gl, {
  width: resolution,
  height: resolution,
  color: true, depth: true
});
this.rttFrameBuffer.attach({
  [GL.COLOR_ATTACHMENT_0]: [this.rttCubemap, GL.TEXTURE_CUBE_MAP_POSITIVE_X],
  [GL.DEPTH_ATTACHMENT]: renderbuffer
});
```

#### More code:
```js
let resolution = 512;
let renderbuffer = new Renderbuffer(gl, {
  format: GL.DEPTH_COMPONENT16,
  width: resolution,
  height: resolution
});
this.rttCubemap = new TextureCube(gl, {
  data: [], //null causes another error here!
  width: resolution, height: resolution,
  format: gl.RGB,
  type: gl.UNSIGNED_BYTE,
});
```

**Comment by Tirondzo** [comment]
The reason is simplier

https://luma.gl/#/documentation/api-reference/webgl-2-classes/framebuffer
Instead of `GL.COLOR_ATTACHMENT_0` it should be `GL.COLOR_ATTACHMENT0` and so on

**Comment by tsherif** [comment]
Yes, that's definitely incorrect. Thanks for letting us know.
