### ISSUE TITLE
Framebuffer setDrawBuffers issue

### ISSUE THREAD

**Issue by Tirondzo** [uber/luma.gl#1099]
```js
this.rttFrameBuffer.update({drawBuffers:[
  GL.COLOR_ATTACHMENT0,
  GL.COLOR_ATTACHMENT1,
  GL.COLOR_ATTACHMENT2
]});
```
Or any other update drawBuffers raises an error.

That's why:
https://github.com/uber/luma.gl/blob/f0e8bc9de0365bf08281c79a4ad69511a30fde21/modules/webgl/src/classes/framebuffer.js#L147
Should be
```js
this._setDrawBuffers(gl, drawBuffers); 
```

**Comment by 1chandu** [comment]
Good find @Tirondzo , would you be able to make a PR.

**Comment by Tirondzo** [comment]
https://github.com/uber/luma.gl/pull/1102

@1chandu, Done.
Also _setReadBuffers had the same issue, fixed that.
