### ISSUE TITLE
Invalid WebGLRenderingContext

### ISSUE THREAD

**Issue by bravecow** [uber/luma.gl#1101]
```js
new Program(document.getElementById('canvas').getContext('webgl'), {
    id: 'my-program',
});
```

fires: Uncaught Error: Invalid WebGLRenderingContext

console.log: `WebGLRenderingContext {canvas: canvas#canvas, drawingBufferWidth: 300, drawingBufferHeight: 150}`
 
And mapbox custom layer:

```js
onAdd(map, gl) {
      this.map = map;
      this.model = new Program(gl, {
          id: 'my-program',
      });
}
```
gives the same error 😐

v: 7.0.1

**Comment by 1chandu** [comment]
Looks like invalid WebGL context, is `gl` valid? can you check its contents.

**Comment by bravecow** [comment]
It works well if I add: `gl._version = 1;`
https://github.com/uber/luma.gl/blob/557d7b46288cdbb803ab349a63e05fad4d50bbc1/modules/webgl/src/webgl-utils/webgl-checks.js#L12

https://jsfiddle.net/vmh64yLo/

**Comment by tsherif** [comment]
luma.gl does some instrumenting and polyfilling that other parts of the system depend on. You should be able to get it working by using the `instrumentGLContext` function from `@luma.gl/webgl`:
```js
import 'instrumentGLContext' from '@luma.gl/webgl';

onAdd(map, gl) {
      instrumentGLContext(gl);
      this.map = map;
      this.model = new Program(gl, {
          id: 'my-program',
      });
}
```

**Comment by bravecow** [comment]
```js
import { instrumentGLContext } from '@luma.gl/webgl';
```
works. thanks 👍
