### ISSUE TITLE
Lessons doesn't work

### ISSUE THREAD

**Issue by bravecow** [uber/luma.gl#1108]
https://luma.gl/#/examples/webgl-lessons/lesson-01-drawing

http://learningwebgl.com/blog/?p=28

![image](https://user-images.githubusercontent.com/988471/57934041-6633b300-78c7-11e9-9dbe-68332be78e13.png)

**Comment by ibgreen** [comment]
As far as I can tell the learningwebgl blog is down. luma.gl lessons are still working. @tsherif

**Comment by tsherif** [comment]
Working for me. learningwebgl.com isn't our site. We just refer to it as a reference for the lessons.

**Comment by bravecow** [comment]
@tsherif yes, it is not your site, but you are referring to broken page 😐 And if you don't have a copy of `learningwebgl.com` to host by yourself, and don't know if they would be available again, maybe it is better to remove dead link.

**Comment by ibgreen** [comment]
Looks like the official github fork for the webgl lessons is https://github.com/tparisi/webgl-lessons which is unlikely to go aways, so we could change the luma.gl lessons to reference the github repo instead.

**Comment by ibgreen** [comment]
@tparisi Are there any plans to revive http://learningwebgl.com/lessons? 

The luma.gl website contains ports of all the lessons to the luma.gl API and we link to the original lessons as reference?

E.g. https://luma.gl/#/examples/webgl-lessons/lesson-01-drawing
