### ISSUE TITLE
Unable to disable WebGL debug in production build

### ISSUE THREAD

**Issue by dev-chr** [uber/luma.gl#1123]
I am running a React project that uses Luma.GL through Deck.Gl, and the console is showing: "luma.gl: WebGL debug support imported" in a production build.

I am going through the documentation, and can't seem to find how to disable the debug mode in a production deployment. 

Thanks!

**Comment by tsherif** [comment]
That should only occur if you explicitly import `@luma.gl/debug` in your application. I don't believe deck.gl does this by default. Is it possible such an import statement made it into your production code somehow?

**Comment by dev-chr** [comment]
> That should only occur if you explicitly import `@luma.gl/debug` in your application. I don't believe deck.gl does this by default. Is it possible such an import statement made it into your production code by mistake?

Thanks for your response!

So it turns out upgrading to Deck.GL > 7.0 fixes this issue. I was running 6.4.X 
Deck.GL < 7 imports the modules differently and forcibly includes debug modules and debug params.

Some previous issues and roadmaps show that debug was planned to be moved into its own module once I kept searching.
