### ISSUE TITLE
Publish new module versions with LICENSE file

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/luma.gl#1129]
As of https://github.com/uber-web/ocular/pull/197, published modules properly include their full license text. deck.gl has [published](https://github.com/uber/deck.gl/issues/3151#issuecomment-497133270) v7.0.10 in response, can luma do the same? Thanks!

**Comment by bclinkinbeard** [comment]
Friendly bump.

**Comment by tsherif** [comment]
Just did this last night :)

7.0.3 modules should all include their licenses.

**Comment by bclinkinbeard** [comment]
You rock, thank you!!
