### ISSUE TITLE
Texture resize force mipmaps option to false

### ISSUE THREAD

**Issue by xintongxia** [uber/luma.gl#1146]
#### Background 

Currently Texture class forces `mipmaps` option to be `false` when calling `resize`, I think it would make more sense to keep `mipmaps` setting as its original value before resizing. `mipmaps = this.mipmaps`

https://github.com/uber/luma.gl/blob/master/modules/webgl/src/classes/texture.js#L198

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment]
Oh yeah, that doesn't make any sense.
