### ISSUE TITLE
Discussion: Add `Scene` (or `Scenes`) class to luma.gl

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#1150]
#### Background 
- Being able to pass the output of the `GLTFScenegraphLoader` directly to places where a luma.gl scenegraph is expected is currently inconvenient/unintuitive.

- A main reason is that the `GLTFScenegraphLoader` does not return a luma.gl ScenegraphNode. It returns an object consisting of `{scenes, animator, gltf}`, where `scenes` may be an array of luma.gl `ScenegraphNode`s (each representing a scenegraph).

- To handle this, the deck.gl `ScenegraphLayer.scenegraph` has undocumented support for that object, "hidden" in the default implementation of an accessor: 

```js
getScene: scenegraph => (scenegraph && scenegraph.scenes ? scenegraph.scenes[0] : scenegraph),
```

- (as a side nit, it always picks scene 0. It does not observe the glTF `scene` field to pick the specified default scenegraph).

### Observations

- Regardless of how it is implemented, this represents an undocumented coupling between luma.gl and deck.gl.
- It also makes the API less intuitive. The "scenegraph" loader does not return a scenegraph (but a wrapper object).

This has been confusing during work on e.g. 3D tiles, as it is not clear from documentation if and how the non-standard output of the GLTFScenegraphLoader can be use with the ScenegraphLayer when called independently, and how it can be replaced with alternative loading mechanisms (e.g. from embedded array buffers).

### Proposals

The current "undocumented coupling" could be removed if the `GLTFScenegraphLoader` returned a `ScenegraphNode` subclass (currently the only documented input to the `ScenegraphLayer`):

1. If we define a new class `Scene` that contains the `animations` field in a `ScenegraphNode` subclass:

```js
class Scene extends Group (extends ScenegraphNode) {
  // inherited props
  // children: ScenegraphNode[],
  // added props
  animations: ...
}
```

2. If we want the `GLTFScenegraphLoader` to preserve all the scenes from the original glTF, we could create a class `SceneList`

```js
class SceneList extends ScenegraphNode {
  scenes: Group[],
  scene: Number
  animations: ...,

  traverse(visitor) {
    visit(scenes[scene || 0];
  }
}
```

3. As a fallback, if we really don't want to add a `Scene` type class, perhaps just add a `userData` or `metadata` field to `ScenegraphNode` and store the animations there, instead of returning a wrapper object.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@tsherif @georgios-uber

**Comment by tsherif** [comment]
A scene class could be interesting to manage "global" scene tasks like bounding volumes and transform hierarchies (though this could probably just go into `Group`). But it shouldn't be built this tightly coupled to the output of the glTF loader. And the scene and animations shouldn't be coupled in this way (animations should be handled separately from what's being animated, so we don't end up having to manage multiple animation systems). 

If the issue is just the discrepancy between the glTF loader's output and the data the SceneGraphLayer expects, then I think it should just be handled at that level, e.g. provide separate functions to load glTF scene vs animations.

**Comment by ibgreen** [comment]
@tsherif Thanks for thinking about this, completely agree the proposal is not perfect, but it would be good to improve the current situation, maybe this discussion can shed some light on our options.

> e.g. provide separate functions to load glTF scene vs animations.

Isn't that too inefficient? Wouldn't it involve loading and decoding the binary GLB file twice for each glTF asset.

> we don't end up having to manage multiple animation systems

Agreed, we should only have one animation system (one API, set of classes, ...). But since the `GLTFScenegraphLoader` is ours, we can make sure that the loaded animations are returned in whatever form that is compatible with our primary animation system.

The fact that some of those animation instances are stored on a scene would not necessarily represent a second animation system.

> And the scene and animations shouldn't be coupled in this way (animations should be handled separately from what's being animated.

Wouldn't separating mean that apps (that could potentially be loading dozens if not hundreds of glTF files) have to add logic to separately extract scene and animations from each gltf file, then have to extract and register them separately with luma.gl? That seems like a lot of boilerplate for the standard task of loading a couple of glTF assets. 

And how is a user going to figure out how to do that with no developer's guide article to explain it?

**Comment by tsherif** [comment]
> Isn't that too inefficient? Wouldn't it involve loading and decoding the binary GLB file twice for each glTF asset.

Could be, depends how the decoding is being done. But more important is that the problem you described is just the interface between two systems that we control, and it makes more sense to me to fix that interface directly then through a proxy class (especially one that represents as general a concept as "the scene") that would then be tied to that interface.

> Wouldn't separating mean that apps (that could potentially be loading dozens if not hundreds of glTF files) have to add logic to separately extract scene and animations from each gltf file, then have to extract and register them separately with luma.gl? That seems like a lot of boilerplate for the standard task of loading a couple of glTF assets.

We could provide utilities to parse data into the right places. But our runtime data structures shouldn't be dictated by one data format we want to support.

**Comment by ibgreen** [comment]
> We could provide utilities to parse data into the right places. But our runtime data structures shouldn't be dictated by one data format we want to support.

Sure I am open to other proposals. Perhaps we should take a step back and start with discussing:
1. whether we agree that the current luma.gl API around glTF loading is too complicated, and 
2. whether we think it needs to be fixed.

As it stands, I personally don't think anyone except deck.gl is going to use the luma.gl glTF support, and that the glTF examples in luma.gl and loaders.gl are not particularly useful.

We do have some user feedback that supports this conclusion: https://github.com/uber-web/loaders.gl/issues/248. 

A reasonable litmus test is looking at the [gltf example code](https://github.com/uber/luma.gl/blob/master/examples/core/gltf/app.js). It is not exactly a pretty "25 liner" (even factoring out the menu related code, which should probably be moved to a separate file).

**Comment by ibgreen** [comment]
Moving discussion to #702 tracker.
