### ISSUE TITLE
Unit test coverage : core/multipass

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#1175]
Following changes are made to core/multipass/* files while writing unit tests in [PR](https://github.com/uber/luma.gl/pull/1176), these needs to verified and make similar changes to other modules/effects

1. Avoid passing `gl` to methods and use `this.gl`
2. `shader-module-pass` : in `_renderPass` method, normalized `passes` are saved in `this.props`, use them instead of `this.module.passes` Also for given `pass`,  access `model` and `uniforms` from `pass.props`, instead of `pass` object.
3. `edgework` effects : variable names `sample` and `texture` are causing compile failures under node, rename them, similar change will be needed in other effects modules.

**Comment by tsherif** [comment]
Multipass has been removed.
