### ISSUE TITLE
Broken Link on Home page

### ISSUE THREAD

**Issue by adriandarian** [uber/luma.gl#1178]
#### Actual Result
Page does not load
#### Expected Result
Should load documentation page
#### Reproduce Steps
Goto the home screen of the website and click the "Get Started" button
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by adriandarian** [comment]
I made a pull request for this #1177

**Comment by 1chandu** [comment]
Seems to be resolved by #1177
