### ISSUE TITLE
How do I free the resources consumed by a multipass renderer?

### ISSUE THREAD

**Issue by mattes3** [uber/luma.gl#1201]
When I create a multipass renderer, framebuffers are created inside the RenderState object. How do I free these framebuffers, i.e. do I need to delete the multipass renderer? If so, how do I do that?

**Comment by ibgreen** [comment]
@mattes3 Great question. Most luma.gl classes have a `delete` method to free up resources, we should probably add a `delete` method to the multipass classes as well. @1chandu
