### ISSUE TITLE
Fix webpack's headless hack to allow use in rollup

### ISSUE THREAD

**Issue by darionco** [uber/luma.gl#1265]
#### Actual Result
Using luma.gl with rollup results in the app crashing at launch with:
```
module is not defined
```
#### Expected Result
The app loads as expected.

#### Reproduce Steps
```
yarn install luma.gl
```
```
import {AnimationLoop} from 'luma.gl';
```

will submit a PR to fix in a minute.

**Comment by ibgreen** [comment]
@darionco We recently fixed rollup support in another repo and the reporter was kind enough to submit an example with a basic rollup integration

https://github.com/uber-web/loaders.gl/tree/master/examples/get-started-rollup

While there is nothing wrong with a one-time fix, something like this helps us keep the support alive.

**Comment by darionco** [comment]
Unfortunately, the problem appears to have been introduced after that example project was created, using the configuration provided by that project I still get the same issue.

Maybe, because it doesn't use luma.gl directly, tree shaking is clearing the offending code?

**Comment by ibgreen** [comment]
> Unfortunately, the problem appears to have been introduced a

That example is in a different vis.gl repository (loaders.gl)

I was just proposing that you copy that example into luma.gl. That way we'd have a way to easily test that bundling with rollup works (we never use it in our day-to-day work).

**Comment by darionco** [comment]
oh, ok, I'll create a new PR for it then.
