### ISSUE TITLE
Creating a scatter plot 

### ISSUE THREAD

**Issue by argenisleon** [uber/luma.gl#1277]
Hi,

I would like to plot millions of points in a scatter plot and apply some techniques to address overplotting. Seems that Kepler apply some of these techniques, but not sure where to start.

Any help?

**Comment by tsherif** [comment]
Hi @argenisleon. You can try this tutorial to get started: https://eng.uber.com/kepler-data-visualization-traffic-safety/

And there's a more comprehensive set of user guides here: https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/a-introduction.md
