### ISSUE TITLE
Remove math.gl dependency from `@luma.gl/core`

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#1287]
`debug` and `addons` modules still depend on math.gl. The `debug` module doesn't really matter since it should not be part of production apps, but:

- [ ] `addons` should also have math.gl dependency removed
- [ ] the scenegraph node should be fixed
    - `node.rotation` should be restored
    - this time using quaternions (copying `quat` function from `gl-matrix`)
    - glTF code in addons should use the quaternion rotation in scenegraph node
- [ ] Upgrade guide should be updated.
- [ ] Docs should mention that user can choose any math library and give examples of math.gl and gl-matrix.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment]
Going to close as core is no longer really its own module. We can assess whether the dependency on math.gl should be reduced in other parts of luma separately.

**Comment by ibgreen** [comment]
Fair, though I think this is an opportunity to really improve the minimal bundle size numbers for luma.gl.

Let me know if you would like me to try to rebase the PR against the new module structure...
