### ISSUE TITLE
Examples not working locally

### ISSUE THREAD

**Issue by 1wheel** [uber/luma.gl#133]
After running:

```
git clone git@github.com:uber/luma.gl.git
cd luma.gl
npm install
npm start
```

and going to an example page (like `http://192.168.1.154:3000/dist/core/instancing/`), there's just an error message: 

```
'import' and 'export' may only appear at the top level (4:0) while parsing /Users/adam/Desktop/luma.gl/dist/bundle.js while parsing file: /Users/adam/Desktop/luma.gl/dist/bundle.js
```

The `dist/core/mandelbrot/` page loads, but `/dist/core/mandelbrot/bundle.js` 404s and the javascript console on the page says `Uncaught ReferenceError: LumaGL is not defined`.

Also - I'm not sure if budo can delay opening a tab until the initial build is complete, but the browser tab that auto opens flickers for 15 seconds as it try to live reload every time a file is generated.

**Comment by ibgreen** [comment]
@1wheel Confirmed, the main example (demo site) on `master` is broken. 

We recently landed luma.gl v3 onto `master` (to support our upcoming deck.gl v4 release) but we still need to do a refresh of the demo site. It's on our list, current plan is to have it done within a week or so.

If that sounds like too long a wait, you might want to give the demo site on the `2.0-release` branch a whirl, it should work better.

**Comment by 1wheel** [comment]
Oh cool - I'll take a look at v2. 

Thanks!
