### ISSUE TITLE
Warning when rendering with vertexCount 0

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#1339]
When rendering (non instanced) with vertex count `0`, webgl generates following warning :

`RENDER WARNING: Render count or primcount is 0.`

This is not an issue when using instanced rendering, no warning is generated when `instanceCount` is `0` (probably WebGL is only checking vertex count).

NOTE: This warning is seen in several deck.gl layer tests, that use empty `data` prop.

**Comment by tsherif** [comment]
Fixed by #1340
