### ISSUE TITLE
SphereGeometry bug with different nlat and nlong

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#1349]
#### Actual Result

![image](https://user-images.githubusercontent.com/2059298/73485677-67731600-4358-11ea-9036-28f47b66c3fb.png)

#### Expected Result
A sphere

#### Reproduce Steps

Go to https://codepen.io/Pessimistress/pen/OJPebyX?editors=0010, change `nlat` in the first line to `10`.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by tsherif** [comment]
Suspect it's this line: https://github.com/uber/luma.gl/blob/master/modules/engine/src/geometries/sphere-geometry.js#L79
