### ISSUE TITLE
SphereGeometry bug with big  nlat and nlong

### ISSUE THREAD

**Issue by shengsword** [uber/luma.gl#1368]
![download](https://user-images.githubusercontent.com/43477415/75651263-fbefd180-5c92-11ea-8eae-fcc9a7a49c3c.png)

Expected Result
A sphere

Reproduce Steps
`new SphereGeometry({nlat: 500, nlong: 500, radius: 2.0})`

**Comment by tsherif** [comment]
This is just the 16-bit indices blowing out. Will post a quick fix to bump the indices up to 32-bit if there are two many vertices.
