### ISSUE TITLE
gltf rendering error, baseColorFactor not rendered

### ISSUE THREAD

**Issue by Insane-neal** [uber/luma.gl#1370]
#### Actual Result
In luma.gl, the color is missing, the baseColorFactor seems not rendered:
![rack_nocolor](https://user-images.githubusercontent.com/6622047/76376002-2c65f880-6382-11ea-8184-668e3fefebfa.png)
#### Expected Result
In blender, the model's color is as expected:
![rack_with_color](https://user-images.githubusercontent.com/6622047/76376026-3982e780-6382-11ea-9d6c-87ff9686c400.png)

#### Reproduce Steps
- The snippet to load the model (Just followed examples)
```javascript
new ScenegraphLayer({
              ...excludeProps(this.props),
              id: this.id,
              scenegraph: load(url, GLTFLoader, { postProcess: true }),
              //getColor: d => d.color || [0, 0, 0],
              getOrientation: d => d.orientation || [0, 0, 0],
              getScale: d => d.scale || [0.5, 0.5, 0.5],
            }),
```
- The gltf model:

[rack_joined.gltf.zip](https://github.com/uber/luma.gl/files/4315726/rack_joined.gltf.zip)

**Comment by Insane-neal** [comment]
Can anyone help with this issue?

**Comment by ibgreen** [comment]
@georgios-uber is this an easy fix?

**Comment by georgios-uber** [comment]
Sure, I'll take a look.
Please note that the rendering between deck.gl and luma.gl is not exactly the same.
Luma.gl has all the advanced lighting modes enabled but in deck we don't use all of them.

**Comment by georgios-uber** [comment]
This is the luma.gl rendering:
![image](https://user-images.githubusercontent.com/25012840/77482221-aebed580-6de2-11ea-8366-b3681985c7a8.png)

To get the same result with deck.gl set `_lighting: 'pbr'` in the layer props.

**Comment by Insane-neal** [comment]
Thanks, set `_lighting: 'pbr'` solved the issue. We also upgrade deck.gl version to 8.1.0
