### ISSUE TITLE
Review picking in luma.gl

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#147]
From discussion in #136 

> Since picking is not generally implemented in luma.gl, do we still want to have this property here

It is used but in deprecated code.
https://github.com/uber/luma.gl/search?utf8=%E2%9C%93&q=isPickable&type=

Also there is a picking example that uses this (the one that shows the different planets)

We should review this functionality - either delete it, or undeprecate it and document it.

**Comment by shaojingli** [comment]
The picking example should have been fixed by #251, #252 and #256
