### ISSUE TITLE
drawMode: 'POINTS' doesn't work

### ISSUE THREAD

**Issue by ZzzD** [uber/luma.gl#162]
![image](https://cloud.githubusercontent.com/assets/21034744/25602790/3235166e-2f29-11e7-888f-e4a2e262cddf.png)
I used a index to decode the vertices position in vert shader,but doesn't work.

when I render this model, it renders nothing, and I got this:
![image](https://cloud.githubusercontent.com/assets/21034744/25602875/b512d102-2f29-11e7-8b17-b87c9fb6edf1.png)

what does it mean 'gl.NONE'?

**Comment by ibgreen** [comment]
@ZzzD I suspect that the `GL.NONE` thing is just an issue with the logging. Both the WebGL constant`GL.POINTS` and `GL.NONE` happens to be equal to `0` . The logging function just sees a `0` and tries to find the name of a WebGL constant whose value matches the number.

> I used a index to decode the vertices position in vert shader,but doesn't work.

Are you initializing you index array? It will be all zeros after `new Float32Array(particleIndex)`. Try
`Float32Array(particleIndex).map((v, i, array) => array[i] = i);`?

Have you supplied the uniforms your shader needs? luma log level 4 should print out tables with values of uniforms and attributes, I don't see that in your log.

**Comment by ZzzD** [comment]
Hello, ibgreen!
I had initialized index array with this:
![image](https://cloud.githubusercontent.com/assets/21034744/25621618/78739686-2f84-11e7-9a5a-ad7727d78211.png)
And I had supplied thr uniforms with this:
![image](https://cloud.githubusercontent.com/assets/21034744/25621716/c34f0046-2f84-11e7-933d-cafa90d083bb.png)
I used the luma.gl with deck.gl and react-map-gl, but when i use pure WebGL without above, it's working just fine, I have spend two day on this issue, So what should i do now?

**Comment by ibgreen** [comment]
> I used the luma.gl with deck.gl and react-map-gl, but when i use pure WebGL without above, it's working just fine, I have spend two day on this issue, So what should i do now?

For my understanding, are you trying to port the wind example to use luma.gl classes instead of raw webgl? Or are you trying to modify the wind example?

Moving the wind example to luma.gl is something we are planning to do. The wind example is still using raw webgl, which is why we haven't merged it to master yet.

**Comment by ZzzD** [comment]
yes, I'm working on port the [wind example](https://github.com/mapbox/webgl-wind) to use luma.gl and mapbox-gl, any suggestion?

**Comment by ibgreen** [comment]
> I'm working on port the wind example to use luma.gl and mapbox-gl, any suggestion?

That is very cool. I'd certainly recommend making one change at a time and verifying that things still work. 

If you had a branch with a commit that works, and a small delta commit that no longer works, I'd be willing to take a look.

**Comment by shaojingli** [comment]
> yes, I'm working on port the wind example to use luma.gl and mapbox-gl, any suggestion?

This is something that the deck.gl team here really wish to do in the very near future. If you have a branch for this, I would also very interested in taking a look.

**Comment by ZzzD** [comment]
I have push this project to my [GitHub](https://github.com/ZzzD/wind-demo),
seem it has some  issue with framebuffer,  
In general，it's render backgroundTexture and particles in framebuffer's texture, and use the framebuffer's texture draw to screen. 
Sorry for my mess code, I should do some Cleaning up, but it's 1'clock morning in china.
thanks for your help

**Comment by ZzzD** [comment]
I used 4 models, when I test the other 3 models  render to screen directly, they are working just fine,
the only issue is 'drawParticles' model doesn't work

**Comment by ibgreen** [comment]
@ZzzD Took a quick look at your repo (with your latest commit). What I see is that you now successfully render the particles once on the screen, and then you get an error when updating the particles.
```
GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.
```
This indicates that you are reading and writing to the same texture. I.e. this won't work:
```
        particlesFB.bind()
        models.drawParticles.render({
                u_particles: particlesFB.texture,
```
The typical solution here is to have create framebuffers and simply "rotate" (swap) them each render frame.

**Comment by ZzzD** [comment]
@ibgreen I have solved this problem, even I can't tell how, I just rewrite some code, maybe there was litter error in my code last night.
I update the [repo](https://github.com/ZzzD/wind-demo)
now the program run exactly what I what, But the effect is not very good, because the texture is blurred when the map is zoomed in, So may it need re-render when the viewport of the map changes, but I don't know is there any way to know the range of latitude and longitude of the browser viewport in deck.gl or react-map-gl?
I kown this is beyond the discussion topic of this ISSUE, maybe I should close this issue and find it out.
thank you for your reply
👍

**Comment by ibgreen** [comment]
> I have solved this problem, even I can't tell how, I just rewrite some code, maybe there was litter error in my code last night.

That looks awesome, congratulations!

Some pointers to get you started on the resolution issue - react-map-gl has an `onViewportChange` callback that gives you lng, lat and zoom, and also a `fitBounds` method. These might give you a start. Also for picking purposes, deck.gl keeps a framebuffer resized to the screen size, you could look at that code. 

The trick will be to feed the right coords into your shaders. Would love to see how you end up doing it, maybe you come up something can be moved back to the frameworks to make this easier for others?
