### ISSUE TITLE
deck.gl layer browser example broken in Safari/FF

### ISSUE THREAD

**Issue by ericsoco** [uber/luma.gl#175]
On master, Safari and FF first throw an error on [this `Float32Array` initialization](https://github.com/uber/luma.gl/blob/master/src/webgl/context-state.js#L109). Getting past that, `this.state.model` is `null` in `ScatterplotLayer` in deck.gl.

I'm not clear on how much effort we're putting into keeping master unbroken across repos, so feel free to file this away for later. However, it's blocking investigation into https://github.com/uber/deck.gl/issues/652.

**Comment by shaojingli** [comment]
@ericsoco We are making every effort to make master unbroken. I'm triaging and investigating
