### ISSUE TITLE
Framebuffer `width` and `height` not updated on `resize()`

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#199]
https://github.com/uber/luma.gl/blob/master/src/webgl/framebuffer.js#L142

Seems that the attachments are resized, but the fields of the Framebuffer object are not updated.
This causes deck.gl's picking to fail when the window resizes.

**Comment by ibgreen** [comment]
@1chandu this should be a quick fix (test case + fix).

**Comment by shaojingli** [comment]
@Pessimistress Thanks for the catch. This should be a quick fix

**Comment by shaojingli** [comment]
@1chandu I'll leave this with you then. It will be a good opportunity to get familiar with our test infrastructure.
