### ISSUE TITLE
Lessons: Add user input controls

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#203]
Some of the lessons take user input using slider/checkboxes, this functionality is currently incomplete in disabled, we need to fix it an enable it to match the behavior with lessons at http://learningwebgl.com.

**Comment by 1chandu** [comment]
cc: @ibgreen @shaojingli

**Comment by 1chandu** [comment]
Moving to 6.0

**Comment by tsherif** [comment]
Closing for now. For the examples, I'd rather put the effort into creating new ones that show more of the feature set.
