### ISSUE TITLE
Understand if gl context shared between lessons

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#205]
We call 'resetContext' during initialization of each lesson, to reset gl state to default, assumption here is that all lessons share same gl context, but looking into the code, gl context is created using 'createGLContext' when AnimationLoop is created, if each lesson is creating one animation loop then gl context shouldn't be shared.

To reproduce this problem, comment out everything in 'resetContext', run lesson08 (enables blending) then run lesson04 (doesn't enable blending), you see blend state is enabled instead of being disabled by default.

**Comment by shaojingli** [comment]
No, the GL context is only created through `createGLContext` when the `AnimationLoop.start()` function is called without a valid GL context in arguments.

Take a look at this line: `this.gl = this.gl || contextParams.gl || this._onCreateContext(contextParams);`

**Comment by ibgreen** [comment]
This was settled. Same canvas => same context.
