### ISSUE TITLE
New shader module system

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#235]
The new system is merged. Now we need to clean it up and roll it out.

High Priority
- [ ] Audit the existing shader modules, clean up naming, remove unfinished modules
- [ ] Merge in any remaining `fp64` changes from deck.gl
- [ ] The ability to set the default shader modules (the `project` module should be attached by default to be backward compatible)
- [x] Make deck.gl use luma.gl's `assembleShaders`. 
- [x] Remove `assembleShaders` from deck.gl

Lower Priority:
- [ ] Update existing examples to use shader modules rather than pre-canned shaders

**Comment by ibgreen** [comment]
Closed by #263. Remaining work is making sure the fp64 test suite still runs. Should be a separate task.
