### ISSUE TITLE
Examples that need fixes for v4.0

### ISSUE THREAD

**Issue by shaojingli** [uber/luma.gl#250]
- [x] Custom Picking

<img width="1278" alt="screen shot 2017-07-05 at 8 19 39 am" src="https://user-images.githubusercontent.com/21322704/27871588-ec9122b0-615a-11e7-967f-bd09b7ec46cc.png">

- [x] Persistence

<img width="1278" alt="screen shot 2017-07-05 at 8 21 35 am" src="https://user-images.githubusercontent.com/21322704/27871607-00dfa4a8-615b-11e7-99fe-b1440bd37491.png">

- [x] Change "Lesson 16" to "Lesson 10" if we decide not to fix lesson 10 - 15 

<img width="281" alt="screen shot 2017-07-05 at 8 23 18 am" src="https://user-images.githubusercontent.com/21322704/27871666-38d9d2de-615b-11e7-91db-83b835927dd7.png">

**Comment by shaojingli** [comment]
Plan to remove the custom picking and persistence example for this release

**Comment by ibgreen** [comment]
Removed and renamed
