### ISSUE TITLE
Avoid accessing canvas properties when possible.

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#255]
We access canvas properties (like canvas.clientWidth, canvas.clientHeight to get logical buffer size), in several places (picking: to set framebuffer size, setting viewport size). Accessing these properties have performance impact : https://gist.github.com/paulirish/5d52fb081b3570c81e3a
We can avoid accessing these elements by either passing width/height to function or adding them to props.

CC: @ibgreen @Pessimistress

**Comment by ibgreen** [comment]
The gl context contains gl.frameBufferWidth and gl.frameBufferHeight. In cases where we just need the current size, let's use those value instead of asking the canvas.

**Comment by ibgreen** [comment]
> The gl context contains gl.frameBufferWidth and gl.frameBufferHeight.

Correction, the members are called `gl.drawingBufferWidth` and `gl.drawingBufferHeight` we should use those instead of `clientWidth and clientHeight`.

**Comment by ibgreen** [comment]
I believe this is implemented.
