### ISSUE TITLE
Verify GL.MIN, GL.MAX blendEquation settings under WebGL1 context.

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#259]
Add test case for GL.MIN, GL.MAX under WebGL1 context, just to make sure the extension is used in that case.

**Comment by 1chandu** [comment]
>  just to make sure the extension is used in that case

@ibgreen , what is the extension here, `GL_EXT_blend_minmax` ?

**Comment by ibgreen** [comment]
Yes the idea is that in luma.gl the application can just use 
```
setParameter({
  blendEquation: GL.MAX
})
```
And under the hood, luma.gl will either use WebGL2 or the extension if available.

There is a also a feature 
`
hasFeature(BLEND_EQUATION_MINMAX)
`
That should be true if WebGL2 or the extension is available.

**Comment by 1chandu** [comment]
#308 added a unit test, remaining for this issue:
 For WebGL1 this new unit test passing could be false positive, verify if state set is successful, we could be just returning the value from cache.

**Comment by 1chandu** [comment]
I verified the calls running the unit test under WebGL1 context, when setting `Min` or `Max` values, we do detect change in cache and call the original `blendEquationSeparate/blendEquation` methods to update the state. So the only remaining thing here is to actual rendering.

**Comment by ibgreen** [comment]
> So the only remaining thing here is to actual rendering.

I am not sure we should. We need to stop somewhere, our goal is not to create a complete validation suite for WebGL. We should test our classes, not WebGL itself. I suspect that we have many other more important holes in our test suite.

**Comment by ibgreen** [comment]
> I verified the calls running the unit test under WebGL1 context, when setting Min or Max values, we do detect change in cache and call the original blendEquationSeparate/blendEquation methods to update the state.

Is that captured by a test case or through manual testing?

**Comment by 1chandu** [comment]
> Is that captured by a test case or through manual testing?

unit test that was added in #308
