### ISSUE TITLE
Any plan for GPGPU?

### ISSUE THREAD

**Issue by dazhi1011** [uber/luma.gl#287]
Noticed that  there was a doc about "GPGPU",but now I can't find it...
Is there any plan for GPGPU by using luma.gl or may be another repository?

**Comment by gnavvy** [comment]
Hi @dazhi1011, yes GPGPU support is still in the roadmap.

In the v4.0.0 release of luma.gl we added a bunch of WebGL2 features including the new Transform Feedback support and a more robust Texture class.

You can find in the luma.gl example folder a transform-feedback example for the basic usages.
https://github.com/uber/luma.gl/tree/master/examples/core/transform-feedback

and the wind demo in deck.gl's example folder for more comprehensive usages of some of the GPGPU features (off-screen rendering for data interpolation, transform feedback with a texture input, etc.)
https://github.com/uber/deck.gl/tree/master/examples/wind

**Comment by ibgreen** [comment]
@dazhi1011  I believe the GPGPU page was moved into the luma.gl v4 release [blog post](http://uber.github.io/deck.gl/blog/2017/introducing-lumagl-v4).

For sure, enabling GPGPU programming was a big driver for the creation of luma.gl v4 and we plan to add more examples, documentation, and API improvements in the near future.

Would be interesting to know if there are any APIs/techniques etc that are of particular interest to you.
