### ISSUE TITLE
Scatterplot layer crashes in Safari

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#291]
This is due to 'gl.bufferData' call crashes on safari when size is 0 (second argument), but works fine on Chrome. Copy pasting email contents describing the issue :

CC: @ibgreen @shaojingli 

> After I upgrade deck.gl version from 4.0.3 to 4.1.0, Safari does not work.
> Here is a situation details.
> 
> deck.gl@4.0.3 and 4.1.0 on Chrome is work well
> deck.gl@4.0.3 on Safari was work well
> Here is a code to use deck.gl
> https://github.com/sideroad/floras/blob/master/src/components/WorldMap.jsx
> Working example
> 
> https://floras.herokuapp.com/en
> 
> Error details
> 
> Safari throw error in scatterplot-layer
> https://github.com/uber/deck.gl/blob/master/src/layers/core/scatterplot-layer/scatterplot-layer.js#L104
> because of this.state.model is null.
> 
> But when I open site on Safari below, no error happen...
> https://uber.github.io/deck.gl/#/examples/core-layers/scatterplot-layer
> https://uber.github.io/deck.gl/#/documentation/layer-catalog/scatterplot-layer
> 
> If there is any good way to debug my code, plz tell me.

**Comment by ibgreen** [comment]
> This is due to 'gl.bufferData' call crashes on safari when size is 0 (second argument)

Can we just force size to 1 when 0? Allocating too much should not break any apps. We can add a comment that this is needed on MacOS.

**Comment by 1chandu** [comment]
With reference to conformance test, by creating zero sized array fixes the issue , I will create PR soon.

https://www.khronos.org/registry/webgl/sdk/tests/conformance/more/functions/bufferData.html?webglVersion=1&quiet=0
https://www.khronos.org/registry/webgl/sdk/tests/conformance/more/functions/bufferDataBadArgs.html?webglVersion=1&quiet=0

**Comment by 1chandu** [comment]
Resolved by #292.
