### ISSUE TITLE
`shaderCache` param does not seem to be used by `Model`

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#299]
All deck.gl layers are sending a `shaderCache` parameter to the `Model` constructor, assuming they will get "pre-compiled" `Shader`s from the cache if a second instance of a layer is created.

But I can not see any code in `Model` that handles the `shaderCache` parameter. 

Somehow this must have regressed when we moved `assembleShaders` from deck to luma.

Caching is important for startup perf on some GPU drivers.

@Pessimistress @shaojingli

**Comment by shaojingli** [comment]
Yes, it's due to our porting of shader module from deck.gl to luma.gl. The shaderCache never worked in luma.gl.. we never connected the wires...
