### ISSUE TITLE
LumaGL should not error out in a node environment

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#3]
@wwwtyro - The code should not crash by trying to access global browser state like window etc that is not available in Node.js.

Even when WebGl is not available:

- createGLContext should through a descriptive Error exception ('WebGL not available') or similar.

- hasWebGL and extension queries should report false

**Comment by wwwtyro** [comment]
@ibgreen I can't assign, so I'll just leave comments - I'm taking this one.

**Comment by wwwtyro** [comment]
#41

**Comment by wwwtyro** [comment]
@ibgreen I think this one can be closed. :)
