### ISSUE TITLE
Vector classes pass wrong parameters to gl-vec* methods

### ISSUE THREAD

**Issue by jianhuang01** [uber/luma.gl#302]
In gl-vec* all methods need 3 parameters(out, a, b), for example
function add(out, a, b) {
    out[0] = a[0] + b[0]
    out[1] = a[1] + b[1]
    out[2] = a[2] + b[2]
    return out
}
In our Vector classes we missed parameter "out" for a lot of methods, such as add, subtract, multiply, divide, etc.
  add(...vectors) {
    for (const vector of vectors) {
      vec3_add(this, vector); // should be vec3_add(this, this, vector)
    }
    this.check();
    return this;
  }

**Comment by ibgreen** [comment]
@jianhuang Good catch!

We are moving our math functions out to a new `math.gl` repo. I invited you, suggest we fix it there and bump luma.gl to use it.

**Comment by jianhuang01** [comment]
@ibgreen The bug is already fixed in math.gl after checking. I imported math.gl to my example code, so I am not blocked. Should I change luma.gl to use math.gl , too?

**Comment by 1chandu** [comment]
@jianhuang01 , is there anything pending for this, if not can you close it, thanks!

**Comment by jianhuang01** [comment]
Yeah, we need remove /src/packages/math from luma.gl and add math.gl dependency, but math.gl has no official release yet. Maybe we need wait until that happens.
