### ISSUE TITLE
`assembleShaders` prepends code to shader defeating GLSL ES 3.00 version directive

### ISSUE THREAD

**Issue by bjornreppen** [uber/luma.gl#304]
I'm working on a deck.gl shader with bit-wise and modulus operators. I am getting errors:

    ^^^ ERROR: '%' : integer modulus operator supported in GLSL ES 3.00 and above only

I have been browsing documentation, but couldn't find anything on specifying shader versions?

**Comment by ibgreen** [comment]
@bjornreppen 

You need to add the following line to your shader
```
#version 300 es
```
to enable the new GLSL language version that comes with WebGL 2 (OpenGL ES 3.0) - which does indeed bring improved support for integer arithmetic.

Note: I believe it needs to be the very first character of your shader (be careful that you don't e.g. insert a newline before it).

For more information, see e.g. [How to update a shader for OpenGL ES 3.0](http://www.shaderific.com/blog/2014/3/13/tutorial-how-to-update-a-shader-for-opengl-es-30)

**Comment by bjornreppen** [comment]
Thanks ibgreen!

I tried that already.  My impression is that the [assemble-shaders.js](https://github.com/uber/luma.gl/blob/98b1b09417fc51c66049469ab668849675287dc4/src/shadertools/lib/assemble-shaders.js) prepends it's stuff to my shader causing the #version define not to appear at the top?

When I add the define all the way at the top, the error message tells me it is at line 68:

    68: #version 300 es
    ^^^ ERROR: 'version' : #version directive must occur before anything else, except for comments and white space

Am I right in guessing there is currently no way to override the #version short of patching the assemble-shaders.js?

**Comment by ibgreen** [comment]
> My impression is that the assemble-shaders.js prepends it's stuff to my shader causing the #version define to no longer appear at the top?

@bjornreppen Yes that sounds like a bug in luma.gl that we need to fix asap. We should add a test case to our test suite that uses version 300 to make sure this doesn't regress.

> Am I right in guessing there is currently no way to override the #version short of patching the assemble-shaders.js?

If this is in your custom deck.gl layer, and you are calling the `Model` constructor directly, an option is to not provide `modules` parameter and instead import and call assembleShaders directly, take the generated shaders and prepend the version line, then pass those in as `vs` and/or `fs` parameters to `Model` constructor. Might be worth a try, and you can always check out the `Model` constructor source code in luma.gl to make sure that things work as I think.

**Comment by 1chandu** [comment]
@bjornreppen, this issue is fixed in 4.0.3 release.

**Comment by bjornreppen** [comment]
Thanks a lot!  Much appreciated!
