### ISSUE TITLE
luma.gl's buffer.getData is not working

### ISSUE THREAD

**Issue by shaojingli** [uber/luma.gl#329]
Please refer to 

https://github.com/uber/deck.gl/blob/attribute-animation/src/lib/attribute-animation.js#L261

and sync with @Pessimistress on the issue

**Comment by 1chandu** [comment]
@Pessimistress , I am assuming you have already tried latest luma.gl as a specific issue related to getData was fixed recently #317. Only other problem I can think of is optional arguments to `getBufferSubData`, luma.gl's implementation uses 0 and length of array when they are not provided, lets sync-up offline.

**Comment by 1chandu** [comment]
@Pessimistress confirm using latest code (this is included in luma 4.0.4 patch release also).

This unit test covers the use case you are using in attribute-animation.js :
https://github.com/uber/luma.gl/blob/c132352cfd3cdc44581bfb57dd01e460672dd59c/test/webgl/buffer.spec.js#L149

**Comment by 1chandu** [comment]
This issue is no longer reproducible, fixed by #317.
