### ISSUE TITLE
New function `Program.setShaders`

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#332]
There is a scenario in deck.gl (switching between 32 and 64 bits layers) where it is useful to update shaders without creating a new program, keeping all the uniforms.

We could support a `Program.setShaders({vs, fs})` that updates one or both shaders and relinks the program, but leaves uniforms intact.

**Comment by jianhuang01** [comment]
We planned to unify 32 & 64 bits shader, don't need this feature anymore.
