### ISSUE TITLE
WebGLDebugUtils crashes in strict mode

### ISSUE THREAD

**Issue by akre54** [uber/luma.gl#345]
For some reason the import to webgl-debug seems to crash on Chrome Windows and I'm assuming it's because it assigns a free global (i.e. no `const` or `window.` before `WebGLDebugUtils`). Is there some way we can sandbox this?

**Comment by ibgreen** [comment]
I suggest we should try to fix it at the source.

I think we should open a PR on the webgl-debug repo, I did get some response from author in a previous exchange, so we might be able to get it landed. 

I should also finish my PR to update the webgl-debug package to WebGL2.

We could make a fork but I don't think the community benefits from that.

**Comment by akre54** [comment]
I opened a pull there but saw it hadn't been updated in a while. I'll defer to you on what you want to do.

**Comment by ibgreen** [comment]
OK let's give the maintainer a couple of days.

**Comment by ibgreen** [comment]
Should be fixed in latest luma.gl
