### ISSUE TITLE
How to stop AnimationLoop after rendering 1 frame

### ISSUE THREAD

**Issue by bjornreppen** [uber/luma.gl#350]
I am struggling to find a simple way to stop animation after a single frame has been rendered.

I tried calling stop() at the bottom of my onRender, but it doesn't seem to have any effect.  A new animation frame is queued unconditionally by _renderFrame()

**Comment by ibgreen** [comment]
@bjornreppen deck.gl calls the renderloop but always checks a dirty flag on LayerManager. If you don't make any changes to your layers, nothing should be rendered and the impact should be very small.

In the upcoming version we have replaced the custom render loop with luma.gl's `AnimationLoop` class. This class has a `stop` method, not sure if this is what you are referring to (are you using alpha releases?), but I suspect it is not accessible to the app. 

We could look into exposing that.

**Comment by bjornreppen** [comment]
I am only using luma (from npm) this time, no deck.gl.  I guess I could do the same in my code as a workaround, implement a dirty flag and return early in my render function.

**Comment by ibgreen** [comment]
Oh sorry, I didn't realize this is the luma.gl repo :) 

You are suggesting that `AnimationLoop.stop()` is broken. That should not be too hard to debug.

**Comment by 1chandu** [comment]
Fixed in #360.
