### ISSUE TITLE
why glsl not fwidth function? i'm use chrome62. webgl version is 2.0

### ISSUE THREAD

**Issue by dytmh** [uber/luma.gl#353]
why glsl not fwidth function? i'm use chrome62. webgl version is 2.0

**Comment by 1chandu** [comment]
do you see any console errors in chrome, in console set luma.log.priority=2 and re-run your app and paste the console output here.

**Comment by dytmh** [comment]
WARNING: 0:63: 'GL_OES_standard_derivatives' : extension is not supported
ERROR: 0:74: 'fwidth' : no matching overloaded function found
ERROR: 0:75: 'dFdx' : no matching overloaded function found

**Comment by ibgreen** [comment]
@dytmh  Did you add `#version 300 es` to the beginning of your shader? If so, it looks like the WebGL1 extension enabling code is being injected in GLSL 3.00 es shaders even when it shouldn't? @1chandu

**Comment by dytmh** [comment]
GPU not supported or windows pc not supported ? my notebook is intel graphics

**Comment by ibgreen** [comment]
People have had similar problems under Windows in IE11. So far we thought it was IE11 specific issue. We'll need to test in Chrome and come back.
