### ISSUE TITLE
i`m draw some line in framebuffer no alpha or lose alpha

### ISSUE THREAD

**Issue by dytmh** [uber/luma.gl#364]
i`m draw some line in framebuffer no alpha or lose alpha,  but draw in screen no problem. 

click open this image
![index](https://user-images.githubusercontent.com/4333197/33415822-2ffabf78-d5d4-11e7-8c48-edd78b292696.png)

![_20171130134032](https://user-images.githubusercontent.com/4333197/33415826-38dba634-d5d4-11e7-9627-0184057b61df.png)

**Comment by 1chandu** [comment]
Looks like your blending is wrong, check your alpha channel value and blend setup.

**Comment by dytmh** [comment]
framebuffer have  anti-aliasing?   @1chandu

**Comment by 1chandu** [comment]
If you mean, `MSAA` render buffer,  no, we don't create multi sampled buffer by default.

**Comment by 1chandu** [comment]
@dytmh, looks like not related to luma.gl, please re-open with more details if you think if this is still an issue.
