### ISSUE TITLE
Generate warnings on unset attributes when using VertexArray

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#387]
In `Program.setBuffers`, we check whether each attribute is bound to a buffer or not, if not a warning is generated. But when using `VertexArray`, no buffers are passed to `Program` , these warnings need to verified by checking buffer binding in `VertexArray` against attribute information (_attributeCount, _attributeLocaitons) in `Program` object. We either need to pass attribute information to VertexArray object method or , get buffer information from VertexArray object and generate warnings in `Program` object.
We also need to cleanup similar logic in `VertexArray` (`__checkBuffers()`).

**Comment by ibgreen** [comment]
Good point. I think we should assess how use of `VertexArray`s impact the API

* In the recent transform feedback PR I saw a `Geometry` class instance without any "geometry". Doesn't make much sense. In this case the `drawMode` could be passed directly to the `Model` (or maybe set in the `VertexArray`. No need to create a geometry object in this case it seems?
