### ISSUE TITLE
Server Side Rendering creates global "window" object during import

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#394]
Reopening https://github.com/uber/deck.gl/issues/1335 here.
CC: @ex3ndr @ibgreen 

Description from above issue:

Right after importing react-map-gl object "window"object "window" in the global scope appears and this breaks a lot of stuff on the server side.

```
console.warn(typeof window);
import 'deck.gl';
console.warn(typeof window);
```

Will output
```
undefined
deck.gl 5.0.2 - set deck.log.priority=1 (or higher) to trace attribute updates
object
```

Workaround is to use dynamic imports and do not import `deck.gl` directly.

**Comment by 1chandu** [comment]
I am running into this issue when running tests.

**Comment by ibgreen** [comment]
If upgrading to latest webgl-debug didn't help, a workaround could be to remember and restore `window` variable just before and after importing webgl-debug. Example in linked deck.gl PR.

**Comment by 1chandu** [comment]
I am seeing this even with latest `webgl-debug` version 2.0.1, some where during the tests `window` is set to `undefined`, digging into it.

**Comment by ibgreen** [comment]
I found an issue in seer under Node. Posting a PR. @balthazar @1chandu
