### ISSUE TITLE
Bad performance on gaming laptop.

### ISSUE THREAD

**Issue by trusktr** [uber/luma.gl#407]
I'm trying the [shadowmap](http://uber.github.io/luma.gl/#/examples/core-examples/shadowmap) example, and on my Alienware 15 R3, the framerate slows down and increases noticeably. So, it's not a consistent framerate: for one second, slower, and for the next second, faster, and it repeats.

I'm even getting this on the simple [movement](http://uber.github.io/luma.gl/#/examples/webgl-lessons/lesson-03-movement) tutorial.

I'm on Windows, and as far as I know, I don't have anything else eating the CPU time, but who knows, I'm on Windows.

Let me try on other OSes and report back...

**Comment by trusktr** [comment]
(A few minutes later) I can't reproduce this with Three.js, even with much more complex examples. Everything is smooth there.

**Comment by ibgreen** [comment]
@trusktr Thanks for reporting! One thing to keep in mind is that luma.gl renders with retina resolution by default. If you have a high-DPI display this can mean you are pushing 4x more pixels than webgl examples from other frameworks. It is possible to modify the example and add the `useDevicePixels: false` option to the `AnimationLoop` to disable this.

Just in case you were able to play around more:
* Was the issue specific to that example? 
* Were you able to test on other OS / monitors and see a pattern?
