### ISSUE TITLE
Deduce vertexCount for model from currently bound buffers.

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#417]
Current `Model` API requires either `vertexCount` or `geometry` to be set during construction time. In layer case `vertexCount` is deduced from `geometry`. When none of these are specified we can deduce this value from currently bound buffer objects (minimum of all buffer element count).

**Comment by 1chandu** [comment]
Not time to work on this moving to 6.0.

**Comment by tsherif** [comment]
@1chandu is this still relevant?

**Comment by ibgreen** [comment]
A lot of code changes have been made and there are new opinions in this area.
