### ISSUE TITLE
npm install error on Win7 - node-gyp and gl

### ISSUE THREAD

**Issue by Mic1** [uber/luma.gl#420]
F:\Program Files\react\proj\luma>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-dev-server@2.11.1" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0
.0".
[4/4] Building fresh packages...
[1/4] ⠂ uglifyjs-webpack-plugin
[2/4] ⠂ gl: MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) ins
[4/4] ⠂ pre-commit
[-/4] ⠂ waiting...
error F:\Program Files\react\proj\luma\node_modules\gl: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: F:\Program Files\react\proj\luma\node_modules\gl
Output:
prebuild-install info begin Prebuild-install version 2.5.0
prebuild-install info looking for local prebuild @ prebuilds\gl-v4.0.4-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\miccross\AppData\Roaming\npm-cache\_prebuilds\https-github.
com-stackgl-headless-gl-releases-download-v4.0.4-gl-v4.0.4-node-v59-win32-x64.tar.gz
prebuild-install http request GET https://github.com/stackgl/headless-gl/releases/download/v4.0.4/gl-v4.0.4-node-v59-win
32-x64.tar.gz
prebuild-install http 404 https://github.com/stackgl/headless-gl/releases/download/v4.0.4/gl-v4.0.4-node-v59-win32-x64.t
ar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.6.1 runtime=node arch=x64 platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.6.1 | win32 | x64
gyp info spawn C:\python27\python.exe
gyp info spawn args [ 'F:\\Program Files\\react\\proj\\luma\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\Program Files\\react\\proj\\luma\\node_modules\\gl\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\Program Files\\react\\proj\\luma\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\miccross\\.node-gyp\\9.6.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\miccross\\.node-gyp\\9.6.1',
gyp info spawn args   '-Dnode_gyp_dir=F:\\Program Files\\react\\proj\\luma\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\miccross\\.node-gyp\\9.6.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\Program Files\\react\\proj\\luma\\node_modules\\gl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\Program Files\\react\\proj\\luma\\node_modules\\gl\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [F:\Program Files\react\proj\luma\node_modules\gl\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\Program Files\react\proj\luma\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\react\\proj\\luma\\node_modules\\node-gyp\\bi
n\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Program Files\react\proj\luma\node_modules\gl

successive yarn install attempts have prompted for just about every version of VisualStudio and the BuildTools  - I have VS2010, 2015, 2017 now installed with all those versions of the standalone tools also ... it cannot seriously want 2005? The problem is "gl": "^4.0.2" which gives the same error on yarn install gl --save. Googling the error with node-gyp produces more data than I can consume - hoping someone is familiar with this one. Have the standalone examples working perfectly. (added: Win 64 - apparently has nod-gyp/MSBuild problems?)

**Comment by ibgreen** [comment]
Closing as this seems related to outdated webpack versions.
