### ISSUE TITLE
Add missing WebGL2 format support.

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#429]
#### Background  
`glFormatToComponents` needs to support WebGL2 formats like, `RED`, `RG` , etc.

#### To Do List 
  - [X] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Unit test

**Comment by ibgreen** [comment]
Also see https://github.com/uber/luma.gl/blob/master/src/webgl/texture.js#L31

**Comment by 1chandu** [comment]
Not a blocker for Aggregation, moving to backlog, will pull it 5.2.0 if needed.

**Comment by tsherif** [comment]
Going to close this for now. We can add more formats as the need comes up.

**Comment by ilan-gold** [comment]
Hello luma.gl, 

Can we potentially add formats?  Specifically, our desire is for unsigned 32 and 16 bit integers.  Is this possible or are there some pitfalls you all were trying to avoid with these?

Ilan

**Comment by ibgreen** [comment]
@ilan-gold Thanks for reaching out. Is your question about integer support specifically about textures? To clarify, do you want to use data textures with integer values? E.g. via the following formats? 

InternalFormat | Format | Type | SourceBytesPer Pixel
-- | -- | -- | --
RGBA16UI | RGBA_INTEGER | UNSIGNED_SHORT | 8
RGBA16I | RGBA_INTEGER | SHORT | 8
RGBA32UI | RGBA_INTEGER | UNSIGNED_INT | 16
RGBA32I | RGBA_INTEGER | INT | 16

(From https://webgl2fundamentals.org/webgl/lessons/webgl-data-textures.html)

Have you tried to use them such that you can pin point where things go wrong?

**Comment by ilan-gold** [comment]
Yes, my question is specifically about textures, and yes, those are the types I am interested.  I would also be interested in the `R` type as well.  Here is the error I get (with the line number):

```
Error: WebGL warning: texImage2D: ArrayBufferView type not compatible with `type`. texture.js:285
Error: WebGL warning: generateMipmap: The texture's base level must be complete. texture.js:211
```

I think the types would need to be added here: https://github.com/uber/luma.gl/blob/master/modules/webgl/src/classes/texture-formats.js but I could be wrong.  Thanks!

**Comment by ilan-gold** [comment]
Hello, while looking for the exact line it was going wrong, I realized I could override the data types in `Texture` (it seems) so I think I am good for now. I see you have #788 (which took me a bit of time to work around) so until I run into anything else odd, I suppose I don't need this although it could be a "nice-to-have."

**Comment by tsherif** [comment]
luma.gl's texture formats are actually fairly limited. You can see that there are many that are explicitly commented out here: https://github.com/uber/luma.gl/blob/master/modules/webgl/src/classes/texture-formats.js#L31-L108

I believe the reasoning for this was to avoid increasing the bundle size for less frequently used formats. If that's still a concern maybe we could export functions that enable additional texture formats.

**Comment by ilan-gold** [comment]
I think the `_deduceParameters` logic allows for overriding once you work out #788 (see https://github.com/uber/luma.gl/blob/master/modules/webgl/src/classes/texture.js#L601, which I believes allow for overriding the output of built-in formats).  Do I have this right? 

In any case, it seems I was able to pass down my data unimpeded down to the shaders and then got an error from webgl about the data type being unrenderable, which is to be expected.  I didn't get the chance to mess around with the shaders yet to parse out if anything else is going on, but I'll probably be focusing on that next week so I can report back if I see anything wonky then.  If I have this wrong, please let me know, and I'd be happy to help out however.
