### ISSUE TITLE
Implement Groups + hierarchical traversal support 

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#44]
Scenegraph.js has limited support for nodes but is currently broken. Ideally we should have a Group element in our model hierarchy that can contain other models and groups. Groups should be able to have local coordinate systems (scale, position, rotation, etc - full 4x4) that should recursively be applied to any child Models as they are traversed.

There should be a traversal method that maintains a matrix stack and push and pops transformation matrices as we recursively walk the tree.

**Comment by ashokkumarsand** [comment]
Could you please provide some example for this

**Comment by ibgreen** [comment]
@ashokkumarsand Just to understand your use case... You want a short code example in the luma.gl API reference about how to use `GroupNode.traverse()` or are you looking for a working Scenegraph example?

**Comment by ashokkumarsand** [comment]
Hi @ibgreen Please look at the snapshot [ ](url
<img width="617" alt="Screenshot 2019-05-09 at 10 35 27 PM" src="https://user-images.githubusercontent.com/3625846/57472346-e2683e00-72aa-11e9-92bd-f33bed4cc9c7.png">
)
