### ISSUE TITLE
Model problem after upgrading to 5.1.4

### ISSUE THREAD

**Issue by tonny2v** [uber/luma.gl#474]
After I upgrade luma.gl and deck.gl to 5.1.4. The trip layer doesn't work anymore. 
It is reported as a problem caused by model problem of luma.gl. The error is shown below.
`TripsLayer.js:72 Uncaught TypeError: Cannot read property 'render' of null`

Here is the getModel function from [deck.gl examples](https://github.com/uber/deck.gl/blob/5.1-release/examples/trips/trips-layer/trips-layer.js)
```javascript
  getModel(gl) {
    return new Model(gl, {
      id: this.props.id,
      vs: tripsVertex,
      fs: tripsFragment,
      geometry: new Geometry({
        id: this.props.id,
        drawMode: 'LINES'
      }),
      vertexCount: 0,
      isIndexed: true,
      onBeforeRender: () => {
        gl.enable(gl.BLEND);
        gl.enable(gl.POLYGON_OFFSET_FILL);
        gl.polygonOffset(2.0, 1.0);
        gl.blendFunc(gl.SRC_ALPHA, gl.ONE);
        gl.blendEquation(gl.FUNC_AD);
      },
      onAfterRender: () => {
        gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
        gl.disable(gl.POLYGON_OFFSET_FILL);
      }
    });
  }
```

**Comment by 1chandu** [comment]
@tonny2v , I just tested in 5.1-release branch (both `npm run start` and `npm run start-local`) and it runs fine. Can you give more details about how you are running this.
Also are there any errors in console? You can also try setting `deck.log.priority=2` and `luma.log.priorirty=2` for more detailed log.

**Comment by jianhuang01** [comment]
@tonny2v clear your local node_modules and install the dependency again, should be good to use latest deck.gl(5.1.4) and luma.gl(5.1.5)

**Comment by tonny2v** [comment]
@1chandu 
After setting the log priorities. I got the following figure from Chrome console. Seems not helpful?
![image](https://user-images.githubusercontent.com/4075851/38124331-73506c08-3413-11e8-8474-3f8f080a5124.png)

**Comment by tonny2v** [comment]
@jianhuang01 I tried delete the whole node_modules directory and reinstall all package again and the problem remains. Previously I installed the default luma.gl and deck.gl version(both 5.1.4) via yarn. Now I tried specifying luma.gl@5.1.5 and deck.gl@5.1.4 and I got the problem. Is it OS related? I am using MacBook 15 late 2016.

**Comment by tonny2v** [comment]
@1chandu @jianhuang01 I checked the example again with the latest version packages. Indeed it worked. Let me check my custom codes again. Should be something wrong in my codes. Thank you very much.
