### ISSUE TITLE
Verify and fix `UniformBufferLayout` class.

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#484]
#### Background 
We have `UniformBufferLayout` but that is never used and verified, going forward we will be using UBO's more and more, this class can come very handy setting up values in UBO buffers.
#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Verify Scalar offsets
  - [x] Verify Vector offsets
  - [ ] Verify Matrix offsets
  - [ ] Verify Struct and Array offsets
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment]
It's now being used in the DOF example and I went over it in #1000
