### ISSUE TITLE
Support web.gl rendering out of main thread

### ISSUE THREAD

**Issue by jianhuang01** [uber/luma.gl#490]
#### Background 
Support rendering with web.gl outside main thread to improve UI performance

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update 
  - [x] Test

**Comment by 1chandu** [comment]
@Pessimistress , this is added in 6.3 as experimental, can we close this or update and move to 7.0 ?

**Comment by Pessimistress** [comment]
Closing since the experimental API has shipped. We can add a new issue for how we want to move this forward in 7.0.
