### ISSUE TITLE
setAttributes method on vertexArray missing or incorrect docs

### ISSUE THREAD

**Issue by SiggyF** [uber/luma.gl#496]
I think I found some inconsistency in the documentation. 

#### Actual Result
The documentation of [vertexArray](https://github.com/uber/luma.gl/blame/2868b5c68d70776da34c6f5cf50c6ec01af91b04/docs/api-reference/webgl/vertex-array.md#L67)  shows an example with a `setAttributes` method of the `vertexArray` instance. Another method that is used is the `update` method. 

#### Expected Result
I would expect `vertexArray` to have a `setAttributes` method or that the setAttributes example is replaced by what is appropriate (not sure what would be appropriate, `setParameters`, `setBuffers`, `setLocations`). I
#### Reproduce Steps
Instantiate a `vertexArray`, check if `setAttributes` method exists. Or add a [test](https://github.com/uber/luma.gl/blob/master/test/src/webgl/vertex-array.spec.js) to the spec file.

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Thanks for pointing this out. Docs are indeed incorrect. Will fix for 5.2 release which should be out within a week.
