### ISSUE TITLE
Some of the lessons don't work anymore; docs are outdated

### ISSUE THREAD

**Issue by aendrew** [uber/luma.gl#503]
#### Actual Result

1. The repo docs say to run `npm start` in repo root; this now just outputs a text file telling user to go to `examples/` directory and `npm install` in relevant sub-directory, meaning it was pointless to `npm install` in the repo root.

2. Lessons 01 and 02 in `examples/lessons` install and start without issue but nothing is rendered to screen. Both these examples lack an `onRender` lifecycle event.

#### Expected Result

The example starts and renders.

#### Reproduce Steps

1. Clone repo
2. cd examples/lessons/01 # Or 02
3. npm i && npm start

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by aendrew** [comment]
Seems like this was broken by a0030a1cb0b63185a4a9bb7117cb3d3f92478fd5

**Comment by ibgreen** [comment]
@aendrew  Thanks for the good feedback:

> Some of the lessons don't work anymore

Apologies:
- As of last night, I just started making final changes on luma.gl examples for the imminent 5.2 release. 
- We do develop luma.gl on the `master` branch, so it occasionally has short-lived regressions.
- If you need a stable environment for examples right now, please check out the `5.1-release` branch.

To make this easier to figure out for newcomers, I am considering:
1.  Updating the [Examples doc page](http://uber.github.io/luma.gl/#/documentation/getting-started/examples) to mention the option of checking out release branches when running examples.
2. Mention release branches in the `npm start` text file.

**Comment by jianhuang01** [comment]
> Seems like this was broken by a0030a1 — reverting to that commit fixes the first two lessons.

Not broken by a0030a1, didn't work before that commit.
