### ISSUE TITLE
Save debug info in gl context

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#550]
#### Background 
We save debug information (vendor, renderer etc) in `gl.luma.info` object during `getGLContextInfo`  but not during `getGLContextInfo2`, we should make sure we save it at least once so applications have access to this information.

#### To Do List 
  - [X] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
Tracked by #727
