### ISSUE TITLE
Move luma.gl website to ocular

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#583]
#### Background 

Time to finally adopt the same doc generator as other vis.gl frameworks. Most work already done

- [x] Update to latest ocular 
- [x] Make sure styling is (reasonably) intact 
- [ ] Restore Info Panel in examples
- [ ] Make sure links between pages still work

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
Moving to 6.2, 6.1 will use website-old.

**Comment by 1chandu** [comment]
Closing this in favor of #756
