### ISSUE TITLE
OES_vertex_array_object emulation does not work in all cases

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#612]
#### Actual Result

The client-side software emulation of the `OES_vertex_array_object` extension introduced in luma.gl v6 does not work correctly in all cases (constants, instanced attributes) in Edge v16 (and presumably headless-gl).

#### Expected Result

Vertex attribute objects (`VertexArray`s) work correctly in all environments.

#### Reproduce Steps

Run deck.gl v6 website examples in Edge 16.

#### Solution Plan

Replace the emulated extension with custom code in `VertexArray` to bind and unbind all attributes. We already have 90% of the code in place to handle TransformFeedback conflicts and overriding global constant values.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

@1chandu @Pessimistress @jianhuang01

**Comment by heshan0131** [comment]
Is there an estimate on the fixes?

**Comment by ibgreen** [comment]
> Is there an estimate on the fixes?

This will be fixed in 6.1, currently slated for Aug 24. Not yet clear if we can fix it in 6.0.

**Comment by ibgreen** [comment]
Necessary changes implemented in `6.1.0-beta.1`, testing on Edge 16 still needed.

**Comment by 1chandu** [comment]
Verify on Safari.

**Comment by ibgreen** [comment]
Verified
