### ISSUE TITLE
Docs say geometry takes `drawType` option rather than `drawMode`

### ISSUE THREAD

**Issue by shirazb** [uber/luma.gl#644]
Hi,

Small issue here. 

The docs for [`Geometry`](https://luma.gl/#/documentation/api-reference/geometry) state that you can specify a `drawType`. For a while, I was seriously confused as to why my very simple geometry was not working. After looking at the source code, it seems the prop is actually called `drawMode`. Changing my code to use this fixed the issue. Have I missed something or do the docs need correcting?

Thanks,
Shiraz

**Comment by ibgreen** [comment]
Fixed on master, will be published as part of 6.1 website update next week.
