### ISSUE TITLE
Make `Attribute` use `Accessor`

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#653]
#### Background 

- We should standardize on the `Accessor` class for all attribute metadata management.
- `Attribute` should focus on allocation of buffers and "multiplexing" of external/internal/constant values.
- Assuming there is some impact on deck.gl which inherits from `Attribute`

**Comment by ibgreen** [comment]
Closing as this is linked from tracker task

**Comment by tsherif** [comment]
This seems to longer be relevant since Attribute is no longer in Luma.
