### ISSUE TITLE
How to use GLTF model？

### ISSUE THREAD

**Issue by dinglei92** [uber/luma.gl#731]
I want to load a GLTF file model, but I don't know how to use it, Is there a relevant example?

**Comment by ibgreen** [comment]
@dinglei92 

glTF support is being implemented right now, but not yet ready. We may have an initial loader available in ~2 weeks.

**Comment by ibgreen** [comment]
Duplicate of #702

**Comment by dinglei92** [comment]
ok, thank you!  I am looking forward.

**Comment by ibgreen** [comment]
Tracking in #702
