### ISSUE TITLE
[Shader Injection] declaration injection position

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#750]
#### Actual Result
Currently, when injecting declarations (`vs:#decl`, `fs:#decl`) into shaders, the code is inserted at the beginning of the shader, see [this line](https://github.com/uber/luma.gl/blob/master/modules/core/src/shadertools/src/lib/inject-shader.js#L11).

If the user wants to inject a function definition, this new function cannot utilize any existing functions that are defined in the target shader, because the new function will be defined before everything else.

#### Expected Result

User injected declarations should be injected before the `main` function.

#### To Do List
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
#774 resolved this.
