### ISSUE TITLE
AnimationLoop.setNeedsRedraw is broken

### ISSUE THREAD

**Issue by tuner** [uber/luma.gl#755]
`AnimationLoop.setNeedsRedraw(reason)` has no effect, as the reason does not reach the `onRender` callback. Only *drawing buffer resized* events work.

The reason appears to be that `animationProps.needsRedraw` gets overwritten with null in `_updateCallbackData`. See:

```
_updateCallbackData() {
    // Update redraw reason
    this.animationProps.needsRedraw = this.needsRedraw; <-- This is later overwritten
    this.needsRedraw = null; <-- with this

    ... height/width/aspect is checked here

    this.animationProps.width = width;
    this.animationProps.height = height;
    this.animationProps.aspect = aspect;

    this.animationProps.needsRedraw = this.needsRedraw; <-- oops

    ...
}
```

**Comment by 1chandu** [comment]
@tuner , thanks for reporting it. Can you please explain your use case in more detail, so this can be fixed.
