### ISSUE TITLE
3d lines rendering

### ISSUE THREAD

**Issue by HeiYanjing** [uber/luma.gl#759]
![image](https://user-images.githubusercontent.com/42837853/47196264-48828780-d392-11e8-938c-9803ee2f352e.png)

recently , I saw this effect render lines for 3D effects ,when roads are rendered by corrdinate datas, red will exist constantly.
If this kind of animation effects can achieved. I think it will use deck.gl and luma.gl。
so ,if it can be come true.Any ideas about this question？need help！

online watting....

**Comment by 1chandu** [comment]
Effects like these need multiple render passes, in 6.2 we added basic support for multi-pass rendering, we will be building on top this in future releases, stay tuned and check our road-map and RFC [docs](https://github.com/uber/luma.gl/tree/master/dev-docs).

**Comment by HeiYanjing** [comment]
@1chandu 6.2 has been released. so ,now ,It is difficult to  achieve this effects?

**Comment by 1chandu** [comment]
@HeiYanjing , as mentioned above, only multi-pass rendering API is added, one has build specific glow/shadow effects using these and to be used in deck.gl layers ,which is not done yet. We are planning on more improved lighting in 7.0, and will be working on extending this in future releases.

**Comment by HeiYanjing** [comment]
@1chandu Thank you for your reply.

**Comment by ajaxengine** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/42837853/47196264-48828780-d392-11e8-938c-9803ee2f352e.png)
> 
> recently , I saw this effect render lines for 3D effects ,when roads are rendered by corrdinate datas, red will exist constantly.
> If this kind of animation effects can achieved. I think it will use deck.gl and luma.gl。
> so ,if it can be come true.Any ideas about this question？need help！
> 
> online watting....

How to implement bloom effect now?
