### ISSUE TITLE
Is this unused function parameter intended?

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [uber/luma.gl#766]
Hi,

I was browsing through the source code and came across this unused function parameter: https://github.com/uber/luma.gl/blob/05263ca5245cffced569bc7e9c8d63ad1e3c78a2/modules/core/src/webgl-context/track-context-state.js#L270-L272

Is it correct like this? From my understanding you would be pushing empty objects onto the state stack instead of the values. I'm probably misunderstanding how the state management works because it would have likely been caught already.

Kind regards,

Tim

**Comment by 1chandu** [comment]
@TimvanScherpenzeel , yes this code is correct here, during push, it will start with empty object and then every time a state is changed, old value gets saved in this object. During the pop, all old values are set back. It is bit tricky but, if you place few breakpoints and follow the code, should be easy to understand.
