### ISSUE TITLE
Deck.gl/luma.gl 6.1/6.3 are not working on my PC (as in Chome, as in Firefox)

### ISSUE THREAD

**Issue by gorshkov-leonid** [uber/luma.gl#798]
**Versions:**
deck.gl 6.3.0(luma.gl 6.3.0), Google Chrome 70.0.3538.110 x64, Firefox 63.0.3 x64, Windows 10 x64

All examples are not working as from [decl.gl](http://deck.gl/#/documentation/deckgl-api-reference/layers/line-layer) side as mine. I was trying to use other versions of deck.gl. And when I used deck.gl 6.1 with property fp64, I got an interesting effect. My screen blinked and everything got worked in all browsers. Why? I compared two logs and found the only difference: 
```
//this is from problematic logs:
context.js:233 luma: WebGL2 context (Google Inc.,ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1))
```

```
//this is from "good" logs
context.js:233 luma: WebGL2 context (Google Inc.,Google SwiftShader)
```

I repeated this experiment multiple times and decide that it is a root cause.

So for good case logged information is:
```
//logInfo(context.js:233)

webGL = "WebGL2"
driver = ""(Google Inc.,Google SwiftShader)""
info = "{"vendor":"Google Inc.","renderer":"Google SwiftShader","vendorMasked":"WebKit","rendererMasked":"WebKit WebGL","version":"WebGL 2.0 (OpenGL ES 3.0 Chromium)","shadingLanguageVersion":"WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)"}"
```

For bad case information is
```
//logInfo(context.js:233)

webGL = ""WebGL2""
driver = ""(Google Inc.,ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1))""
info = "{"vendor":"Google Inc.","renderer":"ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)","vendorMasked":"WebKit","rendererMasked":"WebKit WebGL","version":"WebGL 2.0 (OpenGL ES 3.0 Chromium)","shadingLanguageVersion":"WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)"}"
```

I tried to use webgl1 (`glOptions: {webgl2: false}`), so logged information changed but result became same. There is informtion:
```
webGL = ""WebGL1""
driver = ""(Google Inc.,ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1))""
info = "{"vendor":"Google Inc.","renderer":"ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)","vendorMasked":"WebKit","rendererMasked":"WebKit WebGL","version":"WebGL 1.0 (OpenGL ES 2.0 Chromium)","shadingLanguageVersion":"WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)"}"
```

I reproduced this problem on all deck's examples. E. g. :
* http://deck.gl/#/documentation/deckgl-api-reference/layers/line-layer
* https://deck.gl/#/examples/core-layers/line-layer
* https://github.com/uber/deck.gl/tree/v6.3.0/examples/get-started/pure-js

_but simple examples of webgl programs (with usage webgl api, not deck.gl) as well as other libraries based on webgl like Mapbox are working fine._

Log:
[bad_logs_localhost-1543778367354.log](https://github.com/uber/luma.gl/files/2637296/bad_logs_localhost-1543778367354.log)

Detailed log:
[bad_logs_localhost-1543778367354_detailed.log](https://github.com/uber/luma.gl/files/2637371/bad_logs_localhost-1543778367354_detailed.log)

Detailed System Report:
[Detailed-System-Report.zip](https://github.com/uber/luma.gl/files/2637393/Detailed-System-Report.zip)

DirectX Diagnostic report:
[DxDiag.txt](https://github.com/uber/luma.gl/files/2637394/DxDiag.txt)

Also I collected webgl browser [report](https://browserleaks.com/webgl):

![browserleaks-webgl-2018_11_30-19_03_45](https://user-images.githubusercontent.com/2270831/49344067-0f754c80-f68c-11e8-8723-e77d614f385e.png)

Grey rectangle was not taken by take-screenshot-button, but it exists on my screen:
![image](https://user-images.githubusercontent.com/2270831/49359368-7d9f2b00-f6ef-11e8-92ef-ae144c1d911c.png)

**Can you investigate this problem? Maybe some workaround exists**

**Comment by gorshkov-leonid** [comment]
What I said is not fully true. It is not working, but I can see broken pieces of geometries at the north pole. I think it can help you. 

![image](https://user-images.githubusercontent.com/2270831/49365434-3d947400-f700-11e8-9b27-75b2f7bc9e3a.png)

**Comment by 1chandu** [comment]
@gorshkov-leonid, thanks you for the detailed report.

> driver = ""(Google Inc.,Google SwiftShader)""

This implies your browser is using the Software renderer instead of the GPU Hardware.

Can you try luma.gl examples (without deck.gl involved) :  https://luma.gl/#/examples/overview , and share the console log.

**Comment by gorshkov-leonid** [comment]
@1chandu all examples in https://luma.gl/#/examples/overview are working? So shall I to redirect issue to deck.gl team?

**Comment by 1chandu** [comment]
yeah, given all luma.gl examples are good, let track this using deck.gl issue.
