### ISSUE TITLE
(dev branch) `io/` isn't transpiled causing issues with loading luma.gl

### ISSUE THREAD

**Issue by chrisirhc** [uber/luma.gl#80]
On dev branch, `io/` isn't transpiled since it's out of the `src/` folder. This causes issues with loading the library since it still requires transpilation when consuming the library. 

Ref:
https://github.com/uber/luma.gl/commit/0a8aabee7d5862cc1b4d27ed05d8b578745d9984#commitcomment-17568765

**Comment by chrisirhc** [comment]
@mikolalysenko is there a particular reason for moving io/ into its own folder, this causes issues with consuming the module as there's code in there that needs to be run through babel.

I tried moving io/ into src/io/ (and fixing the import paths), that was one step in making this module useable in my project. Otherwise, I need to run this module through babel on the project consuming this module.

**Comment by ibgreen** [comment]
@chrisirhc We can move it back to src for now. 

Since 90% of luma.gl's dependencies would come from this module, I have been playing with the idea of breaking it out into a separate component. But right now that's more trouble than it's worth.

**Comment by ibgreen** [comment]
@chrisirhc  @AshleyTravers
I've published a round of fixes: luma.gl@2.0.0-beta5 and deck.gl@3.0.0-beta7. Give them a try and let's see if we can close out this ticket.
