### ISSUE TITLE
Add utility methods to support Histopyramid buidling and traversal

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#800]
#### Background 
Required for https://github.com/uber/deck.gl/issues/2182

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Move GPGPU module.
  - [ ] Whats new update 
  - [x] Test

**Comment by Pessimistress** [comment]
How does Histopyramid fit in the scope of this library? Shouldn't it be in deck.gl?

**Comment by 1chandu** [comment]
> How does Histopyramid fit in the scope of this library? Shouldn't it be in deck.gl?

It is generic texture processing algorithm that can be used by deck.gl contour layer, in future for any new GPGPU features that involves texture processing. Intention is to put this in luma.gl's gpgpu module.
