### ISSUE TITLE
Problem with the dependency of latest @babel/runtime helpers

### ISSUE THREAD

**Issue by hijiangtao** [uber/luma.gl#805]
I met a problem when I install and use `deck.gl` I traced the error and found it's a problem of `luma.gl`'s dependency.

#### Actual Result
A error had been throwed as follows:

```
./node_modules/_luma.gl@6.3.1@luma.gl/dist/esm/webgl/sampler.js
Module not found: 
Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in 
'/site/node_modules/_luma.gl@6.3.1@luma.gl/dist/esm/webgl'
```

#### Expected Result
The package should runs well.

#### Reproduce Steps
1. Install `deck.gl` in your project with `npm install deck.gl`(first time, or use @latest tag when install the package) and it should include a dependency named `luma.gl`, the version of them should look like this:

```
"deck.gl": "^6.3.1",
"luma.gl": "^6.3.1"
``` 

2. Run any code that includes deck.gl can reproduce the problem, here is my code (use with React):

```
import React, { Component } from 'react';
import DeckGL, {LineLayer} from 'deck.gl';

class SpatioTemporalMap extends Component {
  render() {
    const viewState = {
      longitude: -122.41669,
      latitude: 37.7853,
      zoom: 13,
      pitch: 0,
      bearing: 0,
    };

    const data = [{sourcePosition: [-122.41669, 37.7853], targetPosition: [-122.41669, 37.781]}];

    const layers = [
      new LineLayer({id: 'line-layer', data}),
    ];

    return (
      <DeckGL viewState={viewState} layers={layers} />
    );
  }
}
  
export default SpatioTemporalMap;
```

3. In order to confirm this is raised by @babel/runtime, I chose another version of `deck.gl` ([v5.0.0](https://github.com/uber/deck.gl/blob/v5.0.0/package.json), in which the version of `luma.gl` is also v5.0.0)， and it runs babel@6.x (rather than v7.0.0 in deck.gl 6.3.1). The error message has gone away.

After search on the Internet, it seems to be a problem of @babel/runtime, quotes @calebj0seph comments of this problem in https://github.com/mui-org/material-ui/issues/12407: 

> This seems to be caused by the v7.0.0-beta.56 release of @babel/runtime, which split part of the package up into @babel/runtime-corejs2. Material-UI lists ^7.0.0-beta.42 as the version range for @babel/runtime, which will select the latest release v7.0.0-beta.56, causing this issue.
> 
> For a quick workaround, you can try npm install --save-exact @babel/runtime@7.0.0-beta.55 if using npm or yarn add @babel/runtime@7.0.0-beta.55 --exact if using Yarn.

What's more, it seems other dependencies of `deck.gl` meets the same problem, such as https://github.com/uber-common/viewport-mercator-project 

I thought downgrade the version of related dependencies should work.

**Comment by hijiangtao** [comment]
Same problem can be found at https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/62 and https://stackoverflow.com/questions/49633019/cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-me

**Comment by hijiangtao** [comment]
It seems @babel/runtime renamed `es6` to `esm` and caused the can't find module problem. See more at https://github.com/babel/babel/pull/8266#issuecomment-445714019 .

Because of the repo I developed itself can't modify its' babel version casually (@babel/runtime before v7.0.0-beta56)， currently I can only copy the folder in `@babel/runtime/helpers/es6` to `@babel/runtime/helpers/esm` and solve the problem temporarily.

**Comment by ibgreen** [comment]
@hijiangtao  

Thanks for reporting! I am going through your info and links, but am a little uncertain about how to fix this for you.

> Because of the repo I developed itself can't modify its' babel version casually (@babel/runtime before v7.0.0-beta56).

Sounds like you are using a beta versions of the babel software. I am not sure it is reasonable to ask other modules like deck.gl to support beta versions of build tools when the official version has been out for months. You should probably focus on upgrading your repo to the official babel 7 version, that will probably save you from problems in more places going forward.

I just freshly installed a deck.gl example using yarn v1.12.3, and it installs `@babel/runtime@7.2.0` (see below). What would you suggest? That we go through all our modules and revert babel to a version before 7.0.0-beta56? That seems like a step backwards and would likely not be good for users who have already upgraded to the official babel 7 version.

If we can help in some other way, let's discuss.

```
[react-webpack-2](master)$npm ls @babel/runtime
├─┬ deck.gl@6.3.1
│ └─┬ @deck.gl/core@6.3.1
│   ├─┬ luma.gl@6.3.1
│   │ └── @babel/runtime@7.2.0  deduped
│   ├─┬ mjolnir.js@2.0.1
│   │ └── @babel/runtime@7.2.0  deduped
│   └─┬ probe.gl@2.0.1
│     └── @babel/runtime@7.2.0  deduped
└─┬ react-map-gl@3.3.9
  ├─┬ math.gl@2.2.0
  │ └── @babel/runtime@7.2.0
  └─┬ viewport-mercator-project@6.1.0
    └── @babel/runtime@7.2.0  deduped
```

**Comment by hijiangtao** [comment]
@ibgreen Well, thanks for your comments.

I think the problem is that the babel version I used (all versions before 7.0.0-beta56, or even in 6.x version) has no `esm` folder like `@babel/runtime/helpers/esm/`, but `luma.gl` and other dependencies of `deck.gl` used @babel/runtime with version of v7.0.0 or later, in which babel had renamed `es6` folder to `esm` (like `@babel/runtime/helpers/es6/`). And your code include this path exactly in files like `/dist/esm/webgl`, so if anyone import another package with different @babel/runtime version (exactly older than v7.0.0-beta56), then will meet the same problem. More details can be found at https://github.com/babel/babel/pull/8266#issuecomment-445716779 

Thanks for your team's efforts in follow up babel's step (like depends on babel's newest version) to allow developers benefits from their new features, and I think it's the right way to keep up with the newest open source libraries, and you don't need to do extra things to make `luma.gl` compatible with older babel. 

I will find some other methods such as upgrade other dependencies' babel version in my project to keep up with babel v7.x, in order to solve this problem. But it's a little pity that someone may face the same problem as me, if he also import a dependency which depends on an older babel version (@babel/runtime).

Thanks again, and I think the issue can be closed, since that's not an internal problem of `luma.gl` or other `deck.gl` related dependencies.
