### ISSUE TITLE
babel-plugin-remove-glsl-comments breaks "// END MODULE_" comment

### ISSUE THREAD

**Issue by jianhuang01** [uber/luma.gl#837]
#### Actual Result
"// END MODULE_" comment is broken, for example if injecting fp32, the code injected is like
#define MODULE_FP32
..... shader code .....
fp32
#### Expected Result
#define MODULE_FP32
..... shader code .....
// END MODULE_fp32

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
I notices, a quick fix is to update babel.config.js to only touch the actual modules:
```
       ['./dev-modules/babel-plugin-remove-glsl-comments', {
-        patterns: ['**/shadertools/**/*.js']
+        patterns: ['**/shadertools/src/modules/**/*.js']
       }]
     ]
   }
```

Also happy to reconsider whether ending each injected module declaration with a comment is actually worthwhile, it kind of goes against the zero comments philosophy of our new babel plugin, and each successive injected plugin will start with a new define anyway.
