### ISSUE TITLE
Push hook is not reporting browser test failure

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#845]
#### Actual Result
When browser test fails, command line shows `
render-test: BrowserTest successfully completed`

#### Expected Result
If browser test fails, test script should fail.

#### Reproduce Steps
Go to `test/browser.js`, insert the following line:

```js
test('Browser tests', t => {
  t.fail('browser');
  ...
});
```

From the command line, run `npm run test`.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
There is an issue with the `tape` test complete callback - it is called multiple times. I think if we can fix that, this will be solved.

**Comment by tsherif** [comment]
@Pessimistress @ibgreen is this still an issue?

**Comment by ibgreen** [comment]
This was fixed in ocular-dev-tools
