### ISSUE TITLE
Buffer accessor does not work as expected

### ISSUE THREAD

**Issue by georgios-uber** [uber/luma.gl#865]
Creating a new buffer like this:

```
const accessor = new Accessor({offset: 0, stride: 8, type: type}) // assume type is correct
new Buffer(gl, {data, accessor}); // assume gl and data are correct
```

Does not process the accessor properly in the following line:

https://github.com/uber/luma.gl/blob/423d16e417a4c6907480618273da97d59b693f65/modules/core/src/core/model.js#L605

One possible solution is to change the line to:
`Object.assign({}, descriptor, descriptor.layout, descriptor.accessor, {`

**Comment by ibgreen** [comment]
I'll take a look at this.

**Comment by ibgreen** [comment]
While not directly addressing the line in question (will still look at that), #869 adds support for using accessors/accessor object to reference buffers, which I believe will address your use case.

```
const buffer = // "interleaved" vertex attributes: 3 floats for position followed by 4 bytes for RGBA
model.setAttributes({
  positions: {buffer, stride: 16, offset: 0, ...}}),
  colors: {buffer, stride: 16, offset: 12, ...}})
}
```

**Comment by georgios-uber** [comment]
Agree but we still need to fix this or update the documentation to say that this is not expected to work.

**Comment by ibgreen** [comment]
Some further thinking: Just change `descriptor.layer` to `descriptor.accessor` in all three places (model variants) for now. This code has not been updated with the change from layouts to accessors which happened quite some time ago, layout no longer exists, this is just a simple bug fix.

```
Object.assign({}, descriptor, descriptor.layout, { 
```

**Comment by georgios-uber** [comment]
@ibgreen done, want to close this now?

**Comment by ibgreen** [comment]
Yes, I am continuing the improvements to Accessor/Buffer API independently of this.
