### ISSUE TITLE
Transform class leaking issue

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#906]
#### Actual Result

The [Transform run (constant Attribute) test](https://github.com/uber/luma.gl/blob/053a39ff544af3323481dfcb6f18633f72ea6f9a/test/modules/core/core/transform.spec.js#L228) breaks [another transform test](https://github.com/uber/luma.gl/blob/053a39ff544af3323481dfcb6f18633f72ea6f9a/test/modules/gpgpu/histopyramid.spec.js#L39) when enabled.

#### Expected Result

`Transform` instances should be strictly independent from each other.

#### Reproduce Steps

- Enable the test in https://github.com/uber/luma.gl/blob/053a39ff544af3323481dfcb6f18633f72ea6f9a/test/modules/core/core/transform.spec.js#L228
- Run headless test `node test/start.js browser-headless`

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by tsherif** [comment]
@1chandu Did you fix this recently. I saw you did some work on the Transform class. If so, please close this.

**Comment by 1chandu** [comment]
Yes, resolved by #1037
