### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by jagernicolas** [uber/luma.gl#915]
Hi,

I would like to produce a small web app (open source, it will be hosted on gitlab) which could load a small number of 3D models (I'm focused on static models) and to allow trough a web interface an user to create a scene with them. The user will not be able to modify trough the 3d view but he will be able to walk around the scene. I plan to select object from a list to edit properties and to have something like "place object at". The 3d models will be within a folder on the servers. The user need to save/load his scene.

Do you think luma.gl would be the right framework for me ?
is it possible to load a model ?
wich format(s) ?
static/animated ? (animated is not mandatory, just want to know if it could be possible)

**Comment by jianhuang01** [comment]
Check this [example](https://luma.gl/#/examples/webgl-lessons/lesson-10-3d-world), looks like that is what you want. Luma.gl is independent from a specific file format, you can parse the format on your own or use our [loaders.gl](https://luma.gl/#/documentation/loaders-reference/obj-loader) which can support several formats.
Luma.gl doesn't support animated model defined in file format like glTF for now.
