### ISSUE TITLE
CPU/GPU frame timers

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#928]
I'd like to track performance of luma.gl in some real world scenes, to supplement the micro-benchmarking we do with probe.gl. First step would be to add GPU and CPU timing to the AnimationLoop class, possibly tracked using the [Stats](https://github.com/uber-web/probe.gl/blob/master/modules/core/src/lib/stats.js) class from probe.gl. 

I'd also like to have a performance-instensive scene to test on. The instancing example on the website is not bad, and I could add a port of this one, which pushes the instance count to 125k using transform feedback:
- https://tsherif.github.io/picogl.js/examples/125kcubes.html

**Comment by tsherif** [comment]
As a part of this, I'd like to remove the GPU timer logic from [base-model](https://github.com/uber/luma.gl/blob/master/modules/core/src/scenegraph/base-model.js#L405-L444), and move it into animation loop. Per-frame render times are generally be more useful than per-model. Plus the logic here is buggy and will skip every other frame, since GPU timer results are never available until at least the next frame.

**Comment by ibgreen** [comment]
Got this comment in email not in the issue (maybe you deleted it, if so ignore):

> As a part of this, I'd like to remove the GPU timer logic from base-model, and move it into animation loop. Per-frame render times are generally be more useful than per-model. Plus the logic here is buggy and will skip every other frame, since GPU timer results are never available until at least the next frame.

Adding per-frame timings sounds great, but is it necessary to choose one or the other? We report per-model timings in seer right now, and I have been using that. 

I am aware that there is an issue with the queries intermittently failing in the current code, can we solve that instead of deleting it? I don't see a problem with only getting results every other frame, we could just keep reporting the last result until we have new data?

**Comment by tsherif** [comment]
I changed the description after our conversation yesterday. I'll focus on creating the per-frame timers and worry about the per-object ones later.

> I am aware that there is an issue with the queries intermittently failing in the current code, can we solve that instead of deleting it? I don't see a problem with only getting results every other frame, we could just keep reporting the last result until we have new data?

Yes, definitely. The problem is that the code [here](https://github.com/uber/luma.gl/blob/master/modules/core/src/scenegraph/base-model.js#L405-L444) is incorrect. It should check for the last frame's results at the beginning of the frame, before checking if it should start a new query. Query results are never available in the same frame in which they began (see section 3.7.12 of the WebGL 2 spec). We can just update that code to use a similar flow to the one [I'm using for frame time](https://github.com/uber/luma.gl/blob/frame-timers/modules/core/src/core/animation-loop.js#L427-L451).

**Comment by ibgreen** [comment]
Sounds good. 

While our general principle is to not add arbitrary extra logic to the WebGL class wrappers, I wonder if moving the handling of `lastGPUTimeQueryReturned` into the `Query` class might be a reasonable exception? Is there a way to do it that is generic enough that it could be part of the general class?

**Comment by tsherif** [comment]
Hmm... that makes sense. It could be more generic, like `lastQueryReturned`, which would be useful for any query.
