### ISSUE TITLE
Allow application to force rendering of a frame

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#936]
#### Background
In some cases it is useful to force rendering of a frame even if Luma doesn't detect that it needs to draw. A simple example is to call toDataURL on a canvas without having to preserve the drawing buffer (which is off by default, as of #931).

**Comment by ibgreen** [comment]
Looking closer, I see that `AnimationLoop` has the `setNeedsRedraw` method so it is part of the "federated" dirty flag system currently in use by deck.gl.

So all we may need to do is call `setNeedsRedraw` to make sure we trigger a rerender next frame...

**Comment by tsherif** [comment]
Ah, interesting. That could be helpful. There are two ways I think we could do the canvas capture. One is to have a method that forces an immediate rendering, so that canvas contents can be captured afterwards, e.g. 
```
function getSnapshot() {
	this.forceRender();
	return this.canvas.toDataURL();
}

```

or return a promise, set the `needsRedraw` flag, then capture canvas contents and resolve the promise at the end of the next frame.

```
function getSnapshot() {
	this.snapshotPromise = new Promise(...);
	this.setNeedsRedraw('Snapshot');
	return this.snapshotPromise;
}
```

First one's more straightforward to use. Second requires less changes to the current render loop. Any preferences?

**Comment by ibgreen** [comment]
How about?

```
function getSnapshot() {
    this.setNeedsRedraw('Snapshot');
	this.render();
	return this.canvas.toDataURL();
}
``

PS - Does the first method always work if `preserveDrawingBuffers` is false? I have a vague, probably incorrect recollection that drawing outside the `requestAnimationFrame` callback in some cases didn't work.

**Comment by tsherif** [comment]
Drawing outside the animation loop will work. It will just generally cause a performance hit because of context switching.
