### ISSUE TITLE
Texture create from solid color breaks

### ISSUE THREAD

**Issue by kvey** [uber/luma.gl#95]
https://github.com/uber/luma.gl/blob/021b244970db81e131bfe2d9b7c42cbe98d9ac66/src/webgl/texture.js#L400

Breaks due to:

https://github.com/uber/luma.gl/blob/021b244970db81e131bfe2d9b7c42cbe98d9ac66/src/webgl/texture.js#L124

**Comment by 1chandu** [comment]
@kvey 
Very old issue, this code has changed a lot since then, closing for now, please reopen with latest details if this is still an issue.
